- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: enable and start the nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: include from common role
  include_role:
    name: common
    #tasks_from: main    

    
# - name: Delete the directory
#   ansible.builtin.file:
#     state: absent
#     path: /usr/share/nginx/html 

# - name: create the directory
#   ansible.builtin.file:
#     state: directory
#     path: /usr/share/nginx/html 

# - name: download the code
#   ansible.builtin.get_url:
#     url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip              
#     dest: /tmp/frontend.zip

# - name: unzip the code
#   ansible.builtin.unarchive:
#     src: /tmp/frontend.zip
#     dest: /usr/share/nginx/html
#     remote_src: yes   

- name: copy expense.conf
  ansible.builtin.template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
  notify:
  - Restart Nginx
  
  